[PHYSICAL_MACHINE]
# Test Disk UIDs (UUIDs/Identifiers)
phy_machine_test_disk_uid = 'scsi-35002538e11714f02'

[PHYSICAL_MACHINE.phy_machine_net_pair]
client_end = 'vh019'
server_end = 'ph051'

[VIRTUAL_MACHINE.vir_machine_cfg.vm.basic]
cpu = 24